Homework1
OlivkaFromHell/epam_python_autumn_2020 pull request #1
Opened 2021-11-10 10:23 UTC by OlivkaFromHell

I've made all tasks
Hope everything is fine

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/sample_project/tests/test_calculator.py
> +def test_positive_case2():
Маленькое улучшение:
Чтобы не дублировать тесты с одинаковой логикой - ты мог создать два теста (положительный и негативный) и параметризовать их с помощью декоратора:
@pytest.mark.parametrize

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task02.py
> +    assert len(data) >= 3, "The sequence length should be more than 3"
в задании сказано, что последовательность:
_"We guarantee, that the given sequence contain >= 0 integers inside."_
Я думаю не стоит ассертить в коде, а сделать обработку блины последовательности и выводить False в данной ситуации

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task02.py
> +    if data[0] != last_fib(data[0]):
не совсем понятно для чего нужна данная проверка

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/tests/test_task02.py
> +def test_negative_case4():
Тест близок к тому, чтобы выявить ошибку из-за которой твоя функция работает некорректно.
Попробуй его исправить или добавить новый

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task02.py
> +            data = data[1:]
Данный код с копированием списка очень снижает производительность кода.
Есть ли способ избежать копирования списков?

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task03.py
> +            values.append(int(line.strip()))
Что будет, если файл с цифрами будет весить 20Гб, а если еще больше?
Подсказка: не лучшее решение хранить все цифры из файла в оперативной памяти

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/tests/test_task03.py
> +    if not find_maximum_and_minimum("files_for_task03/sample_1.txt"):
У тебя три файла с тестовыми данными. Думаю стоит протестировать и их

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task05.py
> +    assert k > 0, "k - is natural number"
Думаю лучше сделать проверку и соответствующий ретёрн, а не ассерт

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task05.py
> +        if max(local_sums) > max_sum:
Зачем тебе каждую итерацию делать проверку, если все равно складываешь все суммы в список?

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task05.py
> +        for j in nums[i : i + k]:
Обрати внимание на строчку в задании:
You need to find a sub-array with length **less equal** to "k", with maximal sum.
Может придумаешь тест, который уронит твою функцию

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task04.py
>  def check_sum_of_four(a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
Код выглядит очень сложным и перегруженным.
Попробуй почитать про такой модуль в питоне как itertools.
Возможно ты найдешь там, что-то полезное, что сократит твой код до минимума =)

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/task04.py
> +    print(sublist_ab, "\n", sublist_cd)
Думаю принты оставлять в данной функции не лучшая идея

2021-11-10 17:52 UTC, megagnom37 commented on lecture_01/hw/sample_project/calculator/calc.py
> +    return not (bool(a & (a - 1)))
Во всех файлах нет одной пустой строки в конце.
Необходимо добавить по код стайлу

2021-11-10 18:01 UTC, megagnom37 requested changes
Отличная работа! Сделай исправления, чтобы все работало корректно.

2021-11-11 13:08 UTC, OlivkaFromHell commented on lecture_01/hw/task02.py
> +    if data[0] != last_fib(data[0]):
Функция last_fib нужна на случай, если на вход подается последовательность фиббоначи не с начала. Для этого нужно сгенерировать все числа до первого числа из последовательности и сравнить. Вычисление посл-ти Фиббоначи реализовал оптимальным по памяти и кол-ву вычислений способом
last_fib возвращает число фибоначи либо равное data[0], либо превосходящее его.
Во втором случае это означает, что data[0] не принадлежит ряду чисел Фиббоначи, а значит и весь data не явл-ся последовательностью фиббоначи.

Добавил это пояснение в функцию last_fib

2021-11-12 17:39 UTC, megagnom37 requested changes
Отличная работа. Глянь два моих вопроса и по возможности ответь

2021-11-12 17:39 UTC, megagnom37 commented on lecture_01/hw/task03.py
> +    return tuple((min_num, max_num))
можно просто вернуть две переменные через запятую. конструктр тюпла выглядит излишним

2021-11-12 17:39 UTC, megagnom37 commented on lecture_01/tests/test_task02.py
> +@pytest.mark.parametrize("test_input", [*data_positive])
Здесь нельзя указать просто data_positive без создания нового списка и распаковки?

2021-11-16 14:57 UTC, megagnom37 approved these changes

2021-11-16 14:57 UTC, merged