Hw2 is done
OlivkaFromHell/epam_python_autumn_2020 pull request #3
Opened 2021-11-16 17:20 UTC by OlivkaFromHell

в hw1.py функций get_longest_diverse_words оказалось довольно сложной, но я попытался ее задокументировать насколько смог

2021-11-19 16:57 UTC, megagnom37 requested changes
Первая проверка. Оставил комменты

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw2.py
> +    if most_common_elem[1] <= len(inp) // 2:
Возможно это излишняя проверка потому что в задании гарантируют, что самый часто встречающийся элемент есть в списке:
_You may assume that the array is non-empty and the most common element
always exist in the array._

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw2.py
> +        Counter(inp).most_common()[-1],
Ты дважды создаешь объект Counter и просишь список с наиболее популярными значениями.
Мб стоит сначала сохранить результат выполнения функции most_common?

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw3.py
> +    # but it returns List[Tuple] instead List[List]
Понимаю. Если хотел однострочник то мог сделать так:
`return list(map(list, product(*args)))`

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw4.py
> +        if result:
Плоха =(
Попробуй придумать тест, который сломает твою функцию.
Местоположение коммента не случайно - это подсказка)

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw5.py
> +            ans.append(arr[i])
Зачем тебе конструировать новый список по одному элементу добавляя в него когда ты можешь просто вернут срез? Во втором случае тоже

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw5.py
> +    ind_start = arr.index(start)
Если передан несуществующий элемент, то разве мы получим адекватный ответ от функции?
Во втором случае тоже

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw1.py
> +                if char not in string.printable:
Есть еще метод isascii() который можно применить к символу.
Не могу сказать честно что из этого лучше работает, но этот метод явно повысил бы читаемость.

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw1.py
> +                        amount = non_ascii[char]
А почему не просто non_ascii[char] += 1?

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw1.py
> +                    unicodedata.category(char)[0] == "P"
не понял зачем эта проверка

2021-11-19 16:57 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw1.py
>  def get_longest_diverse_words(file_path: str) -> List[str]:
Видимо будем созваниваться и будешь объяснять что за страхи тут происходят

2021-11-19 17:07 UTC, megagnom37 requested changes
Добавил еще комментарий

2021-11-19 17:07 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw4.py
> +        key = str(f"{args} +{kwargs}")
Мне кажется не лучший способ представления аргументов

2021-11-19 17:08 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw2.py
> +    if most_common_elem[1] <= len(inp) // 2:
Я просто негодовал по поводу, что условие дали, а на код оно никак не влияет.
Решил все таки ввести такую проверку

2021-11-19 17:29 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw2.py
> +        Counter(inp).most_common()[-1],
согласен. исправил

2021-11-19 17:30 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw3.py
> +    # but it returns List[Tuple] instead List[List]
спасибо! так и знал, что можно было хитрее обернуть

2021-11-20 07:50 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw1.py
> +                    unicodedata.category(char)[0] == "P"
моя ошибка
видимо, в процессе переписывания count_punctuatuin_chars я залез в get_rarest_char

Сама по себе проверка чекает является ли симол unicode пунктуацией
переписал для лучшей читабельности: `unicodedata.category(char).startswith("P")`

2021-11-25 14:48 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw4.py
> +        key = str(f"{args} +{kwargs}")
исправил, добавив сортировку

2021-11-25 14:49 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw1.py
> +                        amount = non_ascii[char]
исправил

2021-11-25 14:50 UTC, olivka86 commented on lecture_02_data_structures_functions/hw/hw5.py
> +            ans.append(arr[i])
сделал через слайсы

2021-11-25 14:50 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/hw/hw5.py
> +    ind_start = arr.index(start)
добавил конструкцию try-except на случай, если элемента не существует

2021-11-25 19:34 UTC, megagnom37 requested changes
4 и 5 задание

2021-11-25 19:34 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw4.py
> +        key = f"{sorted(args)} {sorted(kwargs.items())}"
sorted для args думаю приведет к ошибкам:
Если функция имеет следующий вид foo(a, b).
Мы ее обернем нашим декоратором, и если передадим при вызове foo(1, 2) и foo(2, 1) в твоем случае аргументы будут расценены как одинаковые

2021-11-25 19:34 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw5.py
> +        ind_stop = arr.index(stop)
если stop index не существует?

2021-11-26 15:40 UTC, megagnom37 requested changes
4 задание

2021-11-26 15:40 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw4.py
> +        key = f"{args} {sorted(kwargs.items())}"
модуль inspect
+ аргументы со значением по умолчанию

2021-11-28 10:43 UTC, megagnom37 requested changes
Новые проблемы с заданием по кэшу

2021-11-28 10:43 UTC, megagnom37 commented on lecture_02_data_structures_functions/tests/test_hw4.py
> +    assert val_1 is val_2
Это не доказывает того, что функция не вызывается дважды, а берет значение из кэша

2021-11-28 10:43 UTC, megagnom37 commented on lecture_02_data_structures_functions/hw/hw4.py
> +        return cached_values[key]
Я думаю стоило чуть больше  внимания уделить тестам, потому что они достаточно однотипны.
Есть случай когда твоя функция работает не так как ожидает юзер.
Например:
```
@cache
def get_list_with_number(num: int):
    some_list = [num for _ in range(num)]
    return some_list

my_list = get_list_with_number(3)
print(my_list)
my_list.append(4)
print(my_list)

new_my_list = get_list_with_number(3)
print(new_my_list)
```

2021-11-28 13:05 UTC, OlivkaFromHell commented on lecture_02_data_structures_functions/tests/test_hw4.py
> +    assert val_1 is val_2
переписал с использованием флага. Теперь должен корректно проверять

2021-11-29 14:42 UTC, megagnom37 approved these changes
+

2021-12-07 11:46 UTC, merged