hw3 v1.0
OlivkaFromHell/epam_python_autumn_2020 pull request #4
Opened 2021-11-18 21:07 UTC by OlivkaFromHell

2021-11-19 10:33 UTC, OlivkaFromHell commented
```
def make_filter(**keywords):
    """
        Generate filter object for specified keywords
    """
    filter_funcs = []
    for key, value in keywords.items():

        def keyword_filter_func(item):
            if key in item and item[key] == value:
                pass
            else:
                return False
            return True
        filter_funcs.append(keyword_filter_func)

    return Filter(*filter_funcs)

```

Я сделал вариант, где make_filter возвращает единственную функцию, но на семинаре сказали, что нужно возвращать в фильтр массив функций.
Но реализация выше вызывает каждый раз функцию только по последнему ключу
Ключи на входе: 
{'name': 'Bill', 'type': 'bird'}

Ключи по которым вызывается ф-ия в Filter.apply:
type: bird - первый вызов
type: bird - второй вызов

должно быть:
name: Bill
type: bird

2021-11-26 16:52 UTC, megagnom37 requested changes
Проверил - исправляй) Если будут вопросы - пиши

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task01.py
> +def cache(times: int) -> Callable:
Ты видимо не до конца понял задание.
У тебя должна остаться до сих пор логика кэширующего декоратора, только значения по определенным аргументам должны храниться заданное количество вызовов, а не навсегда

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task02.py
> +    with multiprocessing.Pool(60) as p:
Почему 60?

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task02.py
> +        all_calculations = p.map(slow_calculate, [i for i in range(501)])
А нельзя вместо листа просто передать range(501)?

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task02.py
> +"""
Какое решение работает быстрее?

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task03.py
> +    return Filter(*filter_funcs)
Ты писал, что она работает не совсем корректно у тебя.
Подправь - если нужна будет помощь пиши

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/tests/test_tesk02.py
> +"""Test passed. Code commented because CI exucutes it > 20 sec."""
Ты можешь использовать декоратор skip в pytest чтобы пропустить некоторые тесты, вместо комментирования кода

2021-11-26 16:52 UTC, megagnom37 commented on lecture_03_functional_programming/tests/test_tesk04.py
> +
Надо добавить тесткейсы для твоих двух ифов когда число меньше 0 и когда равно 0.
Не забывай думать о покрытии кода или просто пользуйся тулами для этого типо coverage

2021-11-27 14:29 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task02.py
> +"""
Зависимость не линейная. И время зависит от n.

При n = 20:
- multiprocessing.Pool -> 5 sec
- **multiprocessing.Process -> 4 sec**

При n = 500:
- multiprocessing.Pool -> 23.4 sec
- **multiprocessing.Process -> 25 sec**

При n = 1000:
- multiprocessing.Pool -> 43 sec
- **multiprocessing.Process -> 58 sec**

2021-11-27 14:32 UTC, OlivkaFromHell commented on lecture_03_functional_programming/tests/test_tesk02.py
> +"""Test passed. Code commented because CI exucutes it > 20 sec."""
спасибо!
нам посоветовали ее просто закомментировать

2021-11-27 14:46 UTC, OlivkaFromHell commented on lecture_03_functional_programming/tests/test_tesk04.py
> +
дописал

2021-11-27 14:46 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task02.py
> +        all_calculations = p.map(slow_calculate, [i for i in range(501)])
да, глупость написал

2021-11-27 14:54 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task02.py
> +    with multiprocessing.Pool(60) as p:
Насколько я понимаю, это ограничения железа.
При n > 60 получаю:
`ValueError: need at most 63 handles, got a sequence of length 63`

Находил эмпирическим путем

2021-11-27 15:51 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task01.py
> +def cache(times: int) -> Callable:
исправил

2021-11-27 15:51 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task01.py
> +def cache(times: int) -> Callable:
написать такое решение оказалось даже проще, чем предыдущее, над которым я немного сломал голову

2021-11-28 11:15 UTC, megagnom37 requested changes
Новая проверка - новые замечания)

2021-11-28 11:15 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task01.py
> +                cached_values[key] = [func(*args, **kwargs), times+1]
Если размер твоей последовательности небольшой и неизменяемый, то лучше использовать tuple. 
Он легче и быстрее, чем список

2021-11-28 11:15 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task02.py
> +    with multiprocessing.Pool(60) as p:
Будем обсуждать значит)

2021-11-28 11:15 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task03.py
> +    filter_funcs = [lambda item, key=key, value=value: item.get(key, False) == value for key, value in
1) Эта строчка точно прошла проверку black? Выглядит очень длинной
2) А если key нет в item и вернутся False и значение value тоже False, тогда у тебя будет True. Кажется странно

2021-11-28 11:15 UTC, megagnom37 commented on lecture_03_functional_programming/hw/tests/test_tesk01.py
> +    assert f(1) + f(2) + f(2) + f(2) == 7
Как эти тесты доказывают нам работоспособность функционала кэша?

2021-11-28 11:15 UTC, megagnom37 commented on lecture_03_functional_programming/hw/tests/test_tesk01.py
> +    assert val_2 is not val_3
Не показатель того что тест работает правильно, тебе просто повезло что ты выбрал слишком большие числа

2021-11-28 13:09 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task01.py
> +                cached_values[key] = [func(*args, **kwargs), times+1]
Я так изначально и задумал, но tuple неизменяемый тип данных, а я ниже использую:
`cached_values[key][1] -= 1`

2021-11-28 13:15 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/tests/test_tesk01.py
> +    assert val_2 is not val_3
Почему не показатель, если я намеренно выбрал большие, чтобы продемонстрировать корректность работы?

2021-11-28 13:15 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/tests/test_tesk01.py
> +    assert f(1) + f(2) + f(2) + f(2) == 7
- test_positive_case1: просто показывает корректную работу функции
остальные кейсы не так как задумано работают и  я их перепишу

2021-11-28 14:56 UTC, OlivkaFromHell commented on lecture_03_functional_programming/hw/task03.py
> +    filter_funcs = [lambda item, key=key, value=value: item.get(key, False) == value for key, value in
1. прошла проверку flake8, иначе бы я не смог сделать коммит  (119 символов в конфиге flake8 стоит)
2. Да, изначально использовал str() - пустую строку, но потом подумал, что мне может вернуться по значению как раз таки пустая строка и поменял на False. А такой кейс сразу в голову не пришел.

теперь вместо __False__ я присваиваю does_not_exist, который явл-ся просто object

2021-11-29 14:47 UTC, megagnom37 reviewed
Проверил исправления

2021-11-29 14:47 UTC, megagnom37 commented on lecture_03_functional_programming/hw/task03.py
> +                    keywords.items()]
Почему просто не сделать проверку if?

2021-11-29 14:47 UTC, megagnom37 commented on lecture_03_functional_programming/hw/tests/test_tesk01.py
> +    assert val_2 is not val_3
Тогда нужно было бы описать это в комментах (иначе тому кто будет твои тесты поддерживать не будет понятно почему здесь такие большие числа).
Твой подход с флагами в прошлой домашке был более явным

2021-11-30 11:48 UTC, megagnom37 approved these changes
+

2021-12-07 11:46 UTC, merged