hw4 v1.0
OlivkaFromHell/epam_python_autumn_2020 pull request #5
Opened 2021-11-25 14:40 UTC by OlivkaFromHell

в последней задаче столкнулся  с проблемой, что  аннотация  `-> Generator[str]` выдает мне ошибку при тестировании, хотя я возвращаю str

2021-12-01 15:59 UTC, megagnom37 requested changes
Проверил - исправляй

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_1_read_file.py
> +cwd = os.path.dirname(os.path.realpath(__file__)) + '/'
Посмотри на класс Path из pathlib

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_1_read_file.py
> +    path = cwd + path
Не лучший способ объединения путей.
Либо опять Path либо хотя бы os.path.join

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_1_read_file.py
> +        f.write(text)
Дублирование кода.
Возможно лучше было сделать так. Создать фикстуру которая принимала содержимое файла как аргумент, затем создавала бы файл и возвращала его через yield. Каждый тест принимал бы фикстуру, с разными аргументами с помощью parametrize. После теста фикстура бы удаляла твой файл.

[https://stackoverflow.com/questions/18011902/pass-a-parameter-to-a-fixture-function](url)

2021-12-01 15:59 UTC, megagnom37 commented on lecture_01/tests/test_task03.py
>  def test_positive_case_1(test_input, result):
Как это попало в пуллреквест?

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_2_mock_input.py
> +                </html>"""
Зачем тут текст если страницы не существует)

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_2_mock_input.py
> +        return FakeResponse()
Дублирование кода - думаю можно как то обобщить это

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_3_get_print_output.py
> +
Я посмотрел - эта проверка не доказывает то что мы пишем в stderr и в stdout (я могу показать показать тебе что все логи у тебя пишутся в stderr)
Я либо предложил бы тебе сделать через запись напрямую в дескрипторы, либо настроить хендлеры для логгеров и проверять в тестах как нибудь иначе

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/task_3_get_print_output.py
> +        logging.info(text)
Все пишется в stderr. Надо либо хендлеры добавлять либо делать как-то по другому (без logging).

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/task_4_doctest.py
> +    ans = [str(i) for i in range(1, n + 1)]
Бахнул бы уж однострочник тогда)

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/task_4_doctest.py
> +    """
Кажется не хватает какого то кейса. В какой то if не зашел =(

2021-12-01 15:59 UTC, megagnom37 commented on lecture_04_test/hw/task_5_optional.py
> +            yield str(i)
В задании сказано без использования "if"

2021-12-06 20:09 UTC, olivka86 commented on lecture_04_test/hw/tests/test_task_1_read_file.py
> +    path = cwd + path
решил оба вопроса через:
`path = os.path.join(os.getcwd(), path)`

2021-12-06 20:34 UTC, OlivkaFromHell commented on lecture_01/tests/test_task03.py
>  def test_positive_case_1(test_input, result):
это я обнуржил ошибку в тестах еще и в первом модуле, но поменять ветку забыл.

2021-12-06 20:35 UTC, OlivkaFromHell commented on lecture_04_test/hw/tests/test_task_2_mock_input.py
> +                </html>"""
справедливо

2021-12-06 20:42 UTC, OlivkaFromHell commented on lecture_04_test/hw/task_4_doctest.py
> +    ans = [str(i) for i in range(1, n + 1)]
слишком громоздкий получается

2021-12-06 20:42 UTC, OlivkaFromHell commented on lecture_04_test/hw/task_4_doctest.py
> +    """
исправил. Не было теста для чисел кратным 15

2021-12-06 20:54 UTC, OlivkaFromHell commented on lecture_04_test/hw/task_3_get_print_output.py
> +        logging.info(text)
переписал через os.stdout.write

2021-12-06 20:54 UTC, OlivkaFromHell commented on lecture_04_test/hw/tests/test_task_2_mock_input.py
> +        return FakeResponse()
вынес в global scope переменные

2021-12-07 11:28 UTC, OlivkaFromHell commented on lecture_04_test/hw/task_5_optional.py
> +            yield str(i)
собственного решения не нашел. Сделал как было на лекции. Код полностью понимаю

2021-12-08 13:06 UTC, OlivkaFromHell commented on lecture_04_test/hw/tests/test_task_1_read_file.py
> +        f.write(text)
решил вопрос через текстуру, только используя не yield, а встроенную в pytest tmpdir

2021-12-09 20:51 UTC, megagnom37 approved these changes
Принято

2021-12-09 20:51 UTC, megagnom37 commented on lecture_04_test/hw/tests/test_task_2_mock_input.py
> +def test_positive_case1():
Я бы сделал фикстуру которая возвращала класс с фейковым респонсом в зависимости от входных параметров текста и статус кода. Но это так на будущее - переделывать не надо)

2021-12-12 12:18 UTC, merged