Homework5
OlivkaFromHell/epam_python_autumn_2020 pull request #6
Opened 2021-11-26 09:39 UTC by OlivkaFromHell

Hw5 v1.1

2021-12-05 19:50 UTC, megagnom37 requested changes
Проверил - есть мелкие замечания

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, text: str, days: int):
days надо изменить на deadline.
в задании сказано сохранить названия атрибутов и методов

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, first_name, last_name):
Аннотация типов

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, first_name, last_name):
Аннотация типов

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Что ты этим тестируешь?

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Зачем это?

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Аналогично

2021-12-05 19:50 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +def test_teacher_create_homework(first_name, last_name, text, time):
А где проверка что дедлайн установился корректно?

2021-12-07 11:33 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
тестирую, что с момента создания дз время на исполнение еще не прошло.
Дата создания: 01.01.2021
Дней на исполнение -> 2, 5, 10 или 100 дней
Дата проверки задания: 02.01.2021

в каждом из 4 случаей дедлайн еще не наступил и homework.is_active возвращает True

2021-12-07 11:35 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Чтобы проверить метод Student.do_homework нужно также присвоить значение методу Homework.is_active, которая выполняется внутри метода do_homework
```
    @staticmethod
    def do_homework(homework: Homework):
        if homework.is_active():
            return homework
        print('You are late')
        return None
```

2021-12-07 11:36 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
То же что и с кейсом выше, только на этот раз студент не успел выполнить дз и Student.do_homework возвращает None

2021-12-07 11:37 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
переписал:
`assert not student.do_homework(homework)`
к виду:
`assert student.do_homework(homework) is None`

2021-12-07 11:43 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +def test_teacher_create_homework(first_name, last_name, text, time):
добавил проверку

2021-12-07 11:43 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, text: str, days: int):
изменил

2021-12-07 11:43 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, first_name, last_name):
исправил

2021-12-07 11:43 UTC, OlivkaFromHell commented on lecture_05_oop1/hw/oop_1.py
> +    def __init__(self, first_name, last_name):
исправил

2021-12-08 08:55 UTC, megagnom37 requested changes
Мелкие замечания по тестам

2021-12-08 08:55 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Почему здесь просто не вызвать метод is_active.
Ты его тестируешь но при этом не вызываешь - выглядит максимально странно

2021-12-08 08:55 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Окей, тогда раз ты мокаешь то зачем вычислять булевское значение если ты можешь просто установить его либо в False либо в True? И зачем поля Homework тогда заполнять

2021-12-08 08:55 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    homework.is_active.return_value = datetime.datetime(2021, 1, 2, 0, 0, 0) - homework.deadline < homework.created
Аналогично предыдущему тесту

2021-12-10 08:17 UTC, megagnom37 approved these changes

2021-12-10 08:17 UTC, megagnom37 commented on lecture_05_oop1/hw/tests/test_oop_1.py
> +    monkeypatch.setattr(datetime, 'datetime', datetime_mock)
В этом тесте так как тестируешь студента - то мог замокать домашку, а именно return value для метода is_active. Но это так на будущее - твой вариант тоже допустим

2021-12-12 12:18 UTC, merged