Homework6
OlivkaFromHell/epam_python_autumn_2020 pull request #7
Opened 2021-12-08 13:07 UTC by OlivkaFromHell

2021-12-22 14:48 UTC, megagnom37 requested changes
Проверил - можно исправлять

2021-12-22 14:48 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/tests/test_counter.py
> +    assert user.get_created_instances() == 3
В чем отличие этих двух тестов

2021-12-22 14:48 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/tests/test_counter.py
> +    assert sub_user.get_created_instances() == 0
Сюда добавить бы проверку что у user_class счетчик не сбросился

2021-12-22 14:48 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +            return HomeworkResult(homework, solution, author=self, created=homework.created)
Внимательно читай задание: он принимает 3 атрибута.
Отсюда делаем вывод что created это дата создания HomeworkResult, а не дата создания Homework, что логично

2021-12-22 14:48 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +class Teacher(Student):
Да ты избавился от дублирования, но теперь у тебя преподаватель может делать домашку (казалось бы зачем). Возможно стоит задуматься над более базовом классом - например User или Human

2021-12-22 14:48 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +            cls.homework_done[homeworkresult.homework] = homeworkresult
Мне кажется это должно работать не так - просто исходя из смысла задачи. В твоем случае будет храниться только 1 результат домашки для всех учеников. Тоесть результат домашки второго ученика перетрет результат первого. Встает вопрос - как мы тогда прочекаем, что все сдали домашку?

2021-12-30 00:06 UTC, OlivkaFromHell commented on lecture_06_oop2_exceptions/hw/tests/test_counter.py
> +    assert user.get_created_instances() == 3
во втором тесте (test_user_instance_get_created_instances) должен был тестироваться вызов метода у класса, а не у инстанса, но я забыл это дописать
исправил на:
`assert user_class.get_created_instances() == 3`

2021-12-30 00:08 UTC, OlivkaFromHell commented on lecture_06_oop2_exceptions/hw/tests/test_counter.py
> +    assert sub_user.get_created_instances() == 0
справедливо. Добавил проверку

2021-12-30 01:19 UTC, OlivkaFromHell commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +            return HomeworkResult(homework, solution, author=self, created=homework.created)
да, мой косяк. поправил

2021-12-30 01:19 UTC, OlivkaFromHell commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +class Teacher(Student):
реализовал наследование от класса User

2021-12-30 01:20 UTC, OlivkaFromHell commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +            cls.homework_done[homeworkresult.homework] = homeworkresult
Хотел, чтобы это работало по ключу авторов, но так как нужно группировать по домашним заданиям, сделал словарь типа {ключ: [список homeworkresult]}

2021-12-30 10:18 UTC, megagnom37 requested changes
Проверил - нужно поправить

2021-12-30 10:18 UTC, megagnom37 commented on lecture_06_oop2_exceptions/hw/oop_2.py
> +            cls.homework_done[homeworkresult.homework].append(homeworkresult)
Тут две проблемы:
1. Может храниться несколько результатов домашней работы для одного и того же ученика (мне кажется логичнее было бы хранить последний вариант). 
2. Ты хранишь объекты домашней работы в списке. Затем используешь следующий код:
```python
if len(homeworkresult.solution) > 5 and homeworkresult not in list_of_homework
```
Какова сложность выполнения операции проверки нахождения элемента в списке?
Может стоить рассмотреть иную структуру для хранения результатов домашней работы?

2021-12-30 16:41 UTC, megagnom37 approved these changes
принято

2021-12-31 12:52 UTC, merged