Homework7
OlivkaFromHell/epam_python_autumn_2020 pull request #8
Opened 2021-12-21 18:48 UTC by OlivkaFromHell

2021-12-27 14:41 UTC, megagnom37 reviewed
Проверил - можно править

2021-12-27 14:41 UTC, megagnom37 commented on lecture_07_idiomatic_python/hw/hw1.py
> +
Рекурсивное решение - рекурсия отстой!
Попробуй реализовать решение без рекурсии

2021-12-27 14:41 UTC, megagnom37 commented on lecture_07_idiomatic_python/hw/hw3.py
> -    ...
Как по мне, то решение было бы хорошим, если бы в задании не был явно указан размер поля.
А раз он указан, то можно заранее описать выигрышные комбинации - их всего 8 и проверить их.
Решилось бы все одним циклом

2021-12-30 10:38 UTC, megagnom37 requested changes
Мелкие замечания - можно поправить

2021-12-30 10:38 UTC, megagnom37 commented on lecture_07_idiomatic_python/hw/hw3.py
> +    else:
Зачем этот else?

2021-12-30 10:38 UTC, megagnom37 commented on lecture_07_idiomatic_python/hw/hw3.py
> +    board = [i for j in board for i in j]
в питоне есть функция chain чтобы сделать список плоским

2021-12-30 11:36 UTC, OlivkaFromHell commented on lecture_07_idiomatic_python/hw/hw3.py
> +    else:
глупость. убрал

2021-12-30 11:36 UTC, OlivkaFromHell commented on lecture_07_idiomatic_python/hw/hw3.py
> +    board = [i for j in board for i in j]
буду знать. спасибо

2021-12-30 16:47 UTC, megagnom37 requested changes
Проверил - не работает

2021-12-30 16:47 UTC, megagnom37 commented on lecture_07_idiomatic_python/hw/hw3.py
> +    board = chain(*board)
мне кажется так работать не будет

2022-01-01 09:27 UTC, megagnom37 approved these changes

2022-01-04 13:02 UTC, merged